openapi: 3.0.0
info:
  version: 1.0.0
  title: Go Gin Framework Rest API
  description: Example go using gin framework implementation rest api
  contact:
    name: Restu Wahyu Saputra
    url: https://github.com/restuwahyu13
    email: restuwahyu13@gmail.com
  license:
    name: MIT
    url: https://github.com/restuwahyu13/gin-rest-api/blob/main/README.md
servers:
  - url: 'http://{host}:4000/api/v1'
    description: go service api server endpoint application
    variables:
      host:
        default: localhost
        enum:
          - localhost
paths:
  ############################
  ## REGISTER AUTH ENDPOINT
  ############################
  /register:
    post:
      tags:
        - Auth Endpoint
      summary: Auth Register
      description: register new users account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                  example: restu wahyu saputra
                email:
                  type: string
                  format: email
                  example: restuwahyu13@zetmail.com
                password:
                  type: string
                  format: password
                  example: qwerty123456789
              required:
                - fullname
                - email
                - password
      responses:
        '200':
          description: Register new account successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: number
                  method:
                    type: string
                  message:
                    type: string
                required:
                  - statusCode
                  - method
                  - message
        '400':
          description: |
            Parsing json data failed,
            Generate accessToken failed,
            Sending email activation failed
        '403':
          description: Register new account failed"
        '409':
          description: Email already exist
  ############################
  ## LOGIN AUTH ENDPOINT
  ############################
  /login:
    post:
      tags:
        - Auth Endpoint
      summary: Auth Login
      description: login user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: restuwahyu13@zetmail.com
                password:
                  type: string
                  format: password
                  example: qwerty123456789
              required:
                - email
                - password
      responses:
        '200':
          description: Login successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: number
                  method:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                required:
                  - statusCode
                  - method
                  - message
                  - data
        '400':
          description: |
            Parsing json data failed,
            Generate accessToken failed
        '403':
          description: |
            User account is not active,
            Username or password is wrong
        '404':
          description: User account is not registered
  ############################
  ## ACTIVATION AUTH ENDPOINT
  ############################
  /activation/{token}:
    post:
      tags:
        - Auth Endpoint
      summary: Auth Activation
      description: activation user account
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemF0aW9uIjp0cnVlLCJlbWFpbCI6ImFsZGlraGFuMTNAemV0bWFpbC5jb20iLCJleHBpcmVkQXQiOjE2MTkyNzkyMDksImlkIjoxMX0.jKxrGfrkNrINdixekYGuDKen24LMGgLCnrXLD3R7Yw8
      responses:
        '200':
          description: Activation account success
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: number
                  method:
                    type: string
                  message:
                    type: string
                required:
                  - statusCode
                  - method
                  - message
        '400':
          description: |
            Parsing json data failed,
            User account hash been active please login
        '403':
          description: Activation account failed
        '404':
          description: User account is not exist
  #############################
  ## RESEND TOKEN AUTH ENDPOINT
  #############################
  /resend-token:
    post:
      tags:
        - Auth Endpoint
      summary: Auth Resend
      description: resend new activation token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: restuwahyu13@zetmail.com
              required:
                - email
      responses:
        '200':
          description: Resend new activation token successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: number
                  method:
                    type: string
                  message:
                    type: string
                required:
                  - statusCode
                  - method
                  - message
        '400':
          description: |
            Parsing json data failed,
            Generate accessToken failed,
            Sending email resend activation failed
        '403':
          description: User account is not active
        '404':
          description: Email is not never registered
  #################################
  ## FORGOT PASSWORD AUTH ENDPOINT
  #################################
  /forgot-password:
    post:
      tags:
        - Auth Endpoint
      summary: Auth Forgot
      description: forgot password account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: restuwahyu13@zetmail.com
              required:
                - email
      responses:
        '200':
          description: Forgot password successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: number
                  method:
                    type: string
                  message:
                    type: string
                required:
                  - statusCode
                  - method
                  - message
        '400':
          description: |
            Parsing json data failed,
            Generate accessToken failed,
            Sending email reset password failed
        '403':
          description: |
            User account is not active,
            Forgot password failed
        '404':
          description: Email is not never registered
  #################################
  ## CHANGE PASSWORD AUTH ENDPOINT
  #################################
  /change-password/{token}:
    post:
      tags:
        - Auth Endpoint
      summary: Auth Login
      description: login user account
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemF0aW9uIjp0cnVlLCJlbWFpbCI6ImFsZGlraGFuMTNAemV0bWFpbC5jb20iLCJleHBpcmVkQXQiOjE2MTkyNzkyMDksImlkIjoxMX0.jKxrGfrkNrINdixekYGuDKen24LMGgLCnrXLD3R7Yw8
      responses:
        '200':
          description: Change new password successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: number
                  method:
                    type: string
                  message:
                    type: string
                required:
                  - statusCode
                  - method
                  - message
        '400':
          description: |
            Parsing json data failed,
            Verified activation token failed,
            Confirm Password is not match with Password
        '403':
          description: |
            User account is not active,
            Change new password failed
        '404':
          description: User account is not exist
  #################################
  ## STUDENT ENDPOINT TERITORY
  #################################
  /student:
    #################################
    ## CREATE STUDENT ENDPOINT
    #################################
    post:
      tags:
        - Student Endpoint
      summary: Create Student
      description: create new student account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: restu wahyu saputra
                npm:
                  type: integer
                  format: number
                  example: 201543502291
                fak:
                  type: string
                  example: mipa
                bid:
                  type: string
                  example: tehnik informatika
              required:
                - name
                - npm
                - fak
                - bid
      responses:
        '200':
          description: Create new student account successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: number
                  method:
                    type: string
                  message:
                    type: string
                required:
                  - statusCode
                  - method
                  - message
        '400':
          description: Parsing json data failed
        '401':
          description: accessToken invalid or expired
        '403':
          description: |
            Authorization is required for this endpoint,
            Create new student account failed
        '409':
          description: CREATE_STUDENT_CONFLICT_409
    #################################
    ## RESULTS STUDENT ENDPOINT
    #################################
    get:
      tags:
        - Student Endpoint
      summary: Results All Student
      description: results all student account exists
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Results Students data successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: number
                  method:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                required:
                  - statusCode
                  - method
                  - message
                  - data
        '401':
          description: accessToken invalid or expired
        '403':
          description: Authorization is required for this endpoint
        '404':
          description: Students data is not exists
  ###################################
  ## STUDENT ENDPOINT TERITORY BY ID
  ###################################
  /student/{id}:
    #################################
    ## RESULT STUDENT ENDPOINT
    #################################
    get:
      tags:
        - Student Endpoint
      summary: Result Student
      description: result specific student by id
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
            example: b78bf89d-7748-42c0-b971-3bb7d28d167e
      responses:
        '200':
          description: Result Student data successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: number
                  method:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                required:
                  - statusCode
                  - method
                  - message
                  - data
        '401':
          description: accessToken invalid or expired
        '403':
          description: Authorization is required for this endpoint
        '404':
          description: Student data is not exist or deleted
    #################################
    ## DELETE STUDENT ENDPOINT
    #################################
    delete:
      tags:
        - Student Endpoint
      summary: Delete Student
      description: delete specific student by id
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
            example: b78bf89d-7748-42c0-b971-3bb7d28d167e
      responses:
        '200':
          description: Delete student data successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: number
                  method:
                    type: string
                  message:
                    type: string
                required:
                  - statusCode
                  - method
                  - message
        '401':
          description: accessToken invalid or expired
        '403':
          description: |
            Authorization is required for this endpoint,
            Delete student data failed
        '404':
          description: Student data is not exist or deleted
    #################################
    ## UPDATE STUDENT ENDPOINT
    #################################
    put:
      tags:
        - Student Endpoint
      summary: Update Student
      description: update specific student by id
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
            example: b78bf89d-7748-42c0-b971-3bb7d28d167e
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: restu wahyu saputra
                npm:
                  type: integer
                  format: number
                  example: 201543502291
                fak:
                  type: string
                  example: mipa
                bid:
                  type: string
                  example: tehnik informatika
              required:
                - name
                - npm
                - fak
                - bid
      responses:
        '200':
          description: Update student data sucessfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: number
                  method:
                    type: string
                  message:
                    type: string
                required:
                  - statusCode
                  - method
                  - message
        '400':
          description: Parsing json data failed
        '401':
          description: accessToken invalid or expired
        '403':
          description: |
            Authorization is required for this endpoint,
            Update student data failed
        '404':
          description: Student data is not exist or deleted
  #################################
  #################################
  ## COMPONENTS AUTH TERITORY
  #################################
  #################################
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
